package managers;

import java.io.Serializable;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

/**
 * A class that manages a map of Strings to Strings. NurseManager knows how to 
 * read String objects from a file and how to write its collection of 
 * String to a file.
 * 
 * @author chowder5, ngokare1, caozhi1, alavined
 */
public class NurseManager implements Serializable{

	
	//Auto-generated by Eclipse
	private static final long serialVersionUID = -9053863766545398658L;
	
	private Map<String, String> nurses; //Nurses' passwords by their user name
	
	/**
     * Constructs a new NurseManager that manages a collection of user names
     * and passwords stored in directory dir in file named by fileName.
     * @param dir the directory in which the data file is stored
     * @param fileName the data file containing Person information
     * @throws IOException
     */
	public NurseManager(File dir, String fileName) throws IOException{
		this.nurses = new HashMap<String, String>();
        
        // Populates the list using stored data, if it exists.
        File file = new File(dir, fileName);
        if (file.exists()) {
            this.populate(file.getPath());
        } else {
            file.createNewFile();
        }
    }
	
	/**
     * Adds a map of a nurse's user name to their password to this 
     * NurseManager
     * @param userName the username of the nurse's account
     * @param password the password of the nurse's account
     */
	public void add(String userName, String password) {
        nurses.put(userName, password);
    }

    /**
     * Returns the Nurses managed by this NurseManager.
     * @return nurses a map of all nurses' user name and their password
     */
    public Map<String, String> getNurses() {
        return nurses;
    }
    
    /**
     * A string representation of all nurses in this NurseManager.
     */
    @Override
    public String toString() {
        return "NurseManager [nurses=" + nurses + "]";
    }
    
    /**
     * Populates the map of Strings from the file at path filePath
     * @param filePath the file path of the data file
     * @throws FileNotFoundException
     */
    private void populate(String filePath) throws FileNotFoundException {
        
        Scanner scanner = new Scanner(new FileInputStream(filePath));
        String [] record;
        
        while(scanner.hasNextLine()) {
        	record = scanner.nextLine().split(",");
        	String userName = record[0];
        	String password = record[1];
            nurses.put(userName, password);
        }
        scanner.close();
    }
    
    /**
     * Returns a boolean if the given user name and password is within
     * the map of all nurses.
     * @return the boolean for which if the given user name is a key
     * and the password is the value of the key in the map nurses.
     */
    public boolean isNurse(String userName, String password) {
    	if (nurses.containsKey(userName)) {
    		return (nurses.get(userName).equals(password));
    	}else{
    		return false;
    	}
    }
}
